services:
  spider:
    image: spider-api:latest
    container_name: spider-api
    ports:
      - "8000:8000"  # REST API and MCP-like endpoints
    command: micromamba run -n api python run_combined_server.py
    environment:
      - SPIDER_HOME=/app/spider_tool
      - PYTHONPATH=/app
    volumes:
      - spider_data:/app/spider_tool/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/spider/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bioinformatics_network

  # Docker Registry with MinIO storage
  registry:
    image: registry:2
    container_name: bioinformatics-registry
    ports:
      - "5000:5000"  # Docker registry API
    environment:
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_ACCESSKEY=admin
      - REGISTRY_STORAGE_S3_SECRETKEY=password123
      - REGISTRY_STORAGE_S3_REGION=us-east-1
      - REGISTRY_STORAGE_S3_BUCKET=docker-registry
      - REGISTRY_STORAGE_S3_ENDPOINT=http://minio:9000
      - REGISTRY_STORAGE_S3_FORCEPATHSTYLE=true
      - REGISTRY_HTTP_HOST=http://localhost:5000
    volumes:
      - registry_data:/var/lib/registry
    restart: unless-stopped
    depends_on:
      - minio
    networks:
      - bioinformatics_network

  # MinIO object storage
  minio:
    image: minio/minio:latest
    container_name: bioinformatics-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - bioinformatics_network

  # Future tools can be added here following the same pattern:
  # tool_name:
  #   image: tool_name-api:latest
  #   container_name: tool_name-api
  #   ports:
  #     - "8002:8000"  # Use different ports for each tool
  #   environment:
  #     - TOOL_HOME=/app/tool_name
  #   volumes:
  #     - tool_name_data:/app/tool_name/output
  #   restart: unless-stopped
  #   networks:
  #     - bioinformatics_network

volumes:
  spider_data:
    driver: local
  registry_data:
    driver: local
  minio_data:
    driver: local
  # tool_name_data:
  #   driver: local

networks:
  bioinformatics_network:
    driver: bridge