version: '3.8'

services:
  spider:
    build:
      context: ./tools/spider
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-1.2.0}
      platforms:
        - linux/amd64
        - linux/arm64
    image: spider-api:${VERSION:-1.2.0}
    container_name: spider-api
    ports:
      - "8000:8000"  # REST API and MCP-like endpoints
    command: micromamba run -n api python run_combined_v2.py
    environment:
      - SPIDER_HOME=/app/spider_tool
      - PYTHONPATH=/app
      - VERSION=${VERSION:-1.2.0}
    volumes:
      - spider_data:/app/spider_tool/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/spider/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bioinformatics_network

  # Future tools can be added here following the same pattern:
  # tool_name:
  #   build:
  #     context: ./tools/tool_name
  #     dockerfile: Dockerfile
  #     args:
  #       - VERSION=${TOOL_NAME_VERSION:-latest}
  #     platforms:
  #       - linux/amd64
  #       - linux/arm64
  #   image: tool_name-api:${TOOL_NAME_VERSION:-latest}
  #   container_name: tool_name-api
  #   ports:
  #     - "8001:8000"  # Use different ports for each tool
  #   environment:
  #     - TOOL_HOME=/app/tool_name
  #     - VERSION=${TOOL_NAME_VERSION:-latest}
  #   volumes:
  #     - tool_name_data:/app/tool_name/output
  #   restart: unless-stopped
  #   networks:
  #     - bioinformatics_network

volumes:
  spider_data:
    driver: local
  # tool_name_data:
  #   driver: local

networks:
  bioinformatics_network:
    driver: bridge