services:
  # SPIDER service - Protein druggability prediction
  spider:
    image: spider-api:latest
    container_name: spider-api
    ports:
      - "8000:8000" 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/spider/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bioinformatics_network

  # BLAST service - Protein sequence similarity search
  # NOTE: BLAST_DB_PATH environment variable must be set to a local directory path
  # Example: export BLAST_DB_PATH=./blast_databases
  blast:
    image: blast-api:latest
    container_name: blast-api
    ports:
      - "8001:8000" 
    environment:
      - BLAST_DB_PATH=/blast_db
    volumes:
      - type: bind
        source: ${BLAST_DB_PATH:?BLAST_DB_PATH environment variable is required. Set it to a local directory path, e.g., export BLAST_DB_PATH=./blast_databases}
        target: /blast_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/blastp/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bioinformatics_network

  # Future tools can be added here following the same pattern:
  # tool_name:
  #   image: tool_name-api:latest
  #   container_name: tool_name-api
  #   ports:
  #     - "8002:8000"  # Use different ports for each tool
  #   environment:
  #     - TOOL_HOME=/app/tool_name
  #   volumes:
  #     - tool_name_data:/app/tool_name/output
  #   restart: unless-stopped
  #   networks:
  #     - bioinformatics_network

volumes:
  spider_data:
    driver: local
  blast_db_data:
    driver: local

  # tool_name_data:
  #   driver: local

networks:
  bioinformatics_network:
    driver: bridge