name: api
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - python-multipart
  - pydantic
  - aiofiles 
  
name: blast
channels:
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - blast