name: blast
channels:
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.11
  - blast=2.16.0
  - entrez-direct=22.4
  - ncbi-vdb=3.2.1
  - rpsbproc=0.5.0
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - curl=8.14.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-aarch64=2.44
  - libasprintf=0.25.1
  - libcurl=8.14.1
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.25.1
  - libgomp=15.1.0
  - libidn2=2.3.8
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsqlite=3.50.3
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.1
  - perl=5.32.1
  - perl-archive-tar=3.04
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.15
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.69
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pip=25.1.1
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wget=1.21.4
  - wheel=0.45.1
  - zlib=1.3.1
  - zstd=1.5.7 