name: spider
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.9.23
  - scikit-learn=0.24.1
  - numpy=1.21.6
  - pandas=1.5.3
  - scipy=1.7.0
  - biopython=1.80
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - joblib=1.5.1
  - ld_impl_linux-aarch64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libsqlite=3.50.3
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.1
  - pip=25.1.1
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytz=2025.2
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1 