name: api
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.12.11
  - fastapi=0.116.1
  - uvicorn=0.35.0
  - python-multipart=0.0.20
  - pydantic=2.11.7
  - aiofiles=24.1.0
  - python-dotenv=1.1.1
  - pyyaml=6.0.2
  - rich=14.0.0
  - typer=0.16.0
  - click=8.2.1
  - starlette=0.47.2
  - pydantic-core=2.33.2
  - annotated-types=0.7.0
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - anyio=4.9.0
  - idna=3.10
  - sniffio=1.3.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - httptools=0.6.4
  - uvloop=0.21.0
  - watchfiles=1.1.0
  - websockets=15.0.1
  - rich-toolkit=0.14.8
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - shellingham=1.5.4
  - fastapi-cli=0.0.8
  - fastapi-core=0.116.1
  - markdown-it-py=3.0.0
  - mdurl=0.1.2
  - pygments=2.19.2
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.3.0
  - tzdata=2025b
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - certifi=2025.7.14
  - ld_impl_linux-aarch64=2.44
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.3
  - libuuid=2.38.1
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.1
  - pip=25.1.1
  - python_abi=3.12
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - yaml=0.2.5 